sudo: false
language: ruby
cache: bundler
rvm:
- 2.4.2

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="YOUR_USERNAME" GIT_EMAIL="YOUR_EMAIL" GH_TOKEN=YOUR_TOKEN'
env:
  global:
    secure: "IYw0R2DiBmzeHhxb1/pVlJDQduf5BDgIXuIAZwQCIE9hLEnGY6/pMYtIZ4zUhxw26c0cmpjFmedAKyZoXPtBaU7syuPFZrV8DSAK+q+bcuhW9SeGkqnK2X8oqFNEf4iZXbUHp8n8QbRtGGg96LBLxvVWHV5iRYIOYcP0XafdvSwV5OekmWINxayx8BA40NrJrQY5zc8ObKWZ1/jkRhTpze1TzCI2ts15K5mSITdxkEzPCJB0Ihc4rJfjoo8zpxIfHoQdDRBfeKRUHGGy9WHIQGmechdTOzu1BuordRRK2GnZp0EHccwL/WIzF1/qe/g22ntCySi/7ml5aDzVj/xj71cdoQtoY3l1k0E4jlSv6pqDekiJ7ArKbWraF+fsfbHtbZDuryIpveOnyRDApgJfdW/1/dvjn71OoowUipk7D4jkWXlZKL+/shC/+tCvg+tZo2cLIti2k1U7o4aXF8g6cr+BjXI7vvNHtclZ8dS3+zxBqA/M1VKb+6FOWZmKUVcLhIsFu+X5qGZdznbrtkiAtUu/LAC0EbUiTRh/HEwlk7mR1qJMUSPbuZrZKU+YEZY1Jg7YV7Uv3WdSKMkn84mHPPgZNl/EdC4xv9pXwaMovZsNzmk6brMqbHeqD8jWRlA1HANVn+lPa6WJWr3c1X2NQL+LEe4s1pW8B/6y3sc8xXs="
branches:
  only:
    - master
